import { feedHandlePool } from '@shared/supporters'
import { SUPPORTER_HANDLES } from './supporters'

/**
 * The other four thousand students. One authored post a day from somebody the reader will
 * never meet, dealt off two tables of a hundred-odd — the handles carrying the supporters
 * among them — and an emoji for a face.
 */

/** A message, or one marked so it is never dealt to a supporter's name. */
export type FeedMessage = string | { text: string; strangersOnly: true }

/** Marks a line for the generated names only. */
function strangersOnly(text: string): FeedMessage {
  return { text, strangersOnly: true }
}

/** The line a message shows, whether or not it is marked. */
export function feedMessageText(message: FeedMessage): string {
  return typeof message === 'string' ? message : message.text
}

/** Whether a message is one the supporters' names never say. */
export function isStrangersOnly(message: FeedMessage): boolean {
  return typeof message !== 'string'
}

/** Grab bag id for {@link FEED_HANDLE_POOL}. */
export const FEED_HANDLE_BAG = 'feed.handles'

/** Grab bag id for {@link FEED_MESSAGES}. */
export const FEED_MESSAGE_BAG = 'feed.messages'

/** Grab bag id for {@link FEED_EMOJI}. */
export const FEED_EMOJI_BAG = 'feed.emoji'

const FEED_HANDLES: readonly string[] = [
  'dbergstrom_',
  'twelvepercentmilk',
  'MScott',
  'ophelia.exe',
  'rrrrrosa',
  'tofuenjoyer',
  'califonria.girl',
  'nocturnalgremlin',
  'priyapatel44',
  'thebiglebowitz',
  'wesley_nap',
  'clementine.jpg',
  'bad_at_chemistry',
  'devon.mp3',
  'astridnotasteroid',
  'definitely_not_freddy',
  'ShanksDickton',
  'bennyfromstats',
  'mateo.vasquez',
  'unpaidintern99',
  'FernTheFern',
  'kwame_k',
  'FRESHOBEATS',
  'iris_in_transit',
  'specialist',
  'nadia.nocturne',
  'shimarin',
  'gwenpool',
  'urist_mcstoneballs',
  'raul_rodriguez',
  'redspytf2',
  'tvgamedonkey',
  'big_boss',
  'NakedSnake',
  'panicatthelibrary',
  'anouk_amok',
  'ApertureScience',
  'callum_c_',
  'like_a_dragon',
  'SaoirseOCullen',
  'deadlinedodger',
  'bignutsman',
  'pocketfulofrocks',
  'wren_writes',
  'thirdfloorstairs',
  'omargo',
  'notcaffeinated',
  'jonah_jitters',
  'let_me_solo_her',
  'delphine.b',
  'lecturehallghost',
  'archie_afk',
  'nina_nonstop',
  'vaporeonfan89',
  'theo_theorem',
  'nine_am_never',
  'tryfingerbuthole',
  'felix_forgot',
  'yolanda_y',
  'pip_and_pop',
  'bigchungusman',
  'dundertale',
  'velvet_room_guest',
  'imogenzz',
  'DiamondDogs80',
  'tallulah_playable',
  'jill.stingray'
]

/** The handle bag: the generated names, with every supporter's marbles spread among them. */
export const FEED_HANDLE_POOL = feedHandlePool(FEED_HANDLES, SUPPORTER_HANDLES)

export const FEED_MESSAGES: readonly FeedMessage[] = [
  'someone in the Kendall Library is eating an ENTIRE rotisserie chicken goddamn',
  'floor 4 vending machine gave me 2 bags of chips. not telling anyone which one',
  'whoever is putting googly eyes on the agora statues i love you',
  'lost 40 dollars at BTB arcade to a racing game that is rigged. RIGGED',
  'i legitimately cannot talk to that one girl at CuteTea',
  'Saw a man in a fake mustache and sunglasses at the Agora food court. If that was Freddy I want my tuition back',
  'i saw you take a coin out of the concord fountain. you disgust me',
  'Would you KINDLY SUBMIT THE GROUP DOC',
  'bobbys diner waitress called me sugar and i tipped 30 percent. im down bad man',
  'SEB scheduled a mixer for 8AM. For who. Who is mixing at 8AM. Who is this for',
  'fell asleep in the whitman greenhouse and woke up with a leaf on my face lmao',
  'DO NOT THE NEW FAST EATS SPICY BURRITO MY ASS IS EXPLODE',
  'stalestein open mic qualifies as cruel and unusual punishment',
  'the green hill park geese are NOT friendly stop telling people they are friendly',
  'why are there PUDDLES at the palaestra gym today??',
  'im playing a chess game with a stranger at pino-cola lounge dont disturb the board please',
  '"reserve bank is overrated and overpriced" is what i would say if i were a corporate philistine',
  'went to springmart to grab some toothpasted and ended up with a super cute lamp??? go veridan',
  'so y\'all are actually fucking at club apogee smh',
  'Thorne Auditorium seats had to have been designed by fucking alien jellyfish',
  'sorry to whoever i walked in on boning in elysium your porch light was on',
  'asked the eastern buffet guy if i could eat free and he just said yes?? no questions?? do i look that broke',
  'i used to be a student like you. then i took a midterm to the knee',
  'whoever put the bra on the venus statue: CAPC had it down in 45 seconds. they have a guy. they have a guy for this',
  'Can we discuss the hygiene optics on rubbing the Venus statue foot? you couldn\'t dare me to',
  'girls will go to selkie with a towel, a book, sunscreen, a speaker and 3 friends and then sit on their phone for 4 hours',
  'sat in front of the jellyfish tank at riverside aquarium for like 2 hours. i think i\'m one of them now',
  'Pier 44 smells like how The Last of Us looks',
  'we really doing hotel dreams discourse? ah shit, here we go again',
  'Stay your ass out of Riverside mall you weirdo couples, I\'m trying to shop',
  'anyone elses money just disappear when you go to lotterdale market',
  'how the F do they keep the plants from falling off the ceiling at the veridan museum',
  'pastel palace bag ripped. RIP macarons. 10 dollars on the sidewalk',
  'lumiere fusion dumplings live in my head rent free but i cant afford them',
  'can future cinema show something else than superhero slop ffs',
  'girl down the hall talks about herself in third person now. help',
  'just sat through 90 min of the wrong lecture. the notes are decent tho',
  'professor made a joke and looked directly at me for the laugh. i laughed. i\'m weak',
  'fast eats tacos tonight. pray for my colon',
  strangersOnly('Duchess is so cute!! I want those tentacles on me!!!'),
  'Hesitation is defeat.',
  'Cherry Concord Pino-Cola tastes like cough syrup. I have had four today. Maybe I will have a fifth',
  'midnight showing of a silent speech at future cinema had 3 people in it and all 3 of us were crying by the end. i don\'t want to talk about it',
  'i don\'t know if I have homework until i look inside the website. Schrodinger\'s education',
  'finally nabbed an apogee shift. time to mix drinks and change lives',
  'nobody asked questions about my presentation ARE YOU NOT ENTERTAINED?',
  'The struggle towards the heights is enough to fill a freshman\'s heart. One must imagine a VU student happy.',
  'why yall so stingy with your tokens at BTB?? LET IT RIDE!',
  'bitches be crazy man. bitches be FUCKING crazy',
  'lowrise 4 kitchen. sandwich over the sink at 1am. peak dining',
  'The intent is to provide VU students with a sense of pride and accomplishment for unlocking different coping strategies.',
  'raised my hand 4 times in lecture. no one hears a word i say... i feel... invisible.',
  'left my exam notes in the kendall terminal. For those who come after.',
  'headphones died. had to hear my own thoughts for 15 minutes. not recommended',
  'all it takes to keep a man happy is to fill his belly and drain his balls.',
  'week 2 and im already behind lol',
  'guys the rumors about hotel dreams massages are true holy moly how is this legal',
  'Left a flower at Girl at the Window like everyone says to. She got a boyfriend 2 days later. Fuck this museum',
  'guy took my agora study pod booking so i stood over him and said hello there. he did not get it. i sat down anyway',
  'meet me where gold crosses rose. bring my hoodie back. bring my dignity too if you find it',
  'me: im not going to club apogee tonight. me at 1am puking on the glass floor 40 stories up:',
  strangersOnly(
    'learned about the guy who cured STIs today and if i could meet one guy in history i\'d blow him. imagine having to worry about that shit'
  ),
  ' i don\'t want peace. i want PROBLEMS ALWAYS',
  'the library printer is jammed AGAIN. i have class in 6 minutes YOU FRICK',
  'whoever wrote my october notes was smart. wish i could ask them',
  strangersOnly('stop being insecure about ur dick. i just want it inside me shut up'),
  'day 4 of attempting to summon my persona. per...so...na...',
  'Why are we still doing 8AMs? Just to suffer?',
  'wake the fuck up samurai. we got an essay to write',
  'the fox girl was right. glasses ARE really versatile.',
  'I\'m a person who wishes to live a very quiet life.',
  'Hot take: dating sims are awesome.',
  'Lumiere Fusion charged us 200 bucks to eat PAPER again. The waiter said it was "conceptual". I ate the paper. It was paper.',
  'i can\'t BELIEVE the high scores out on the new PARADISO track already yall are fucking unemployed',
  'the lowrise 3 cake is a lie',
  'to the girl i ran into 4 times today im not stalking you i promise',
  'Hey, you, you\'re finally awake. You were trying to take PHIL101, right? Fell asleep right in lecture, same as us, and that freshman over there.',
  'bunny bot keeps saying i have no bitches well WHERE ARE YOURS?? WHERE ARE THEY? I DONT SEE EM',
  'saw my high school ex at the agora and walked into a door',
  'my calendar says im in a meeting rn. i am in bed',
  'dude, the lowrise 4 unlimited bread bowl... bread makes you fat? fuckkkk',
  'prof said "this wont be on the exam" and half the room just left',
  'Stop leaking the kendall library makeout spots to the freshman those are national secrets',
  'a venus quad squirrel took my granola bar out of my hand. out of my HAND',
  'in the apogee club. straight up "jorking it" and by "it", haha, well. let\'s justr say. My peanits',
  'to whoever does the pino-cola lounge crossword: 14 across is wrong',
  'these group project hoes ain\'t loyal',
  'got a reserve bank vault seat!!! for march 2028',
  'idc what people say about it Hotel DREAMS is cash only and charges by the hour. Most honest business in Veridan',
  'group project partner submitted nothing. you were the chosen one. you were supposed to destroy the free riders not join them',
  'bunny bot: you have to be at least Good in her preferred stat. me: brother i am not even Decent',
  'ill have a number 9, a number 9 large, a number 6 with the Fast Eats special dip, a Big Burger, large chili fries, Pancho Punch on the side',
  'theres a dude in my class who wears an eyepatch and only says kept you waiting huh',
  'guitar guy in the lowrise 2 courtyard is back and hes actually good this time',
  'i don\'t like the selkie sand. It\'s coarse and rough and irritating and it gets everywhere.',
  'this stalestein twisted lager hangover must be the work of an enemy stand',
  'I AM THORNE. THORNE ART I.',
  'two people in my lab shared a calculator yesterday and i think theyre dating now',
  'quirked up freshman with a little bit of swag busts it down sexual style.. is he goated with the sauce?',
  'not to get political but where WAS Gondor when the Westfold fell??',
  'Let\'s say, hypothetically, for the sake of argument, that I am "gpamaxxing".',
  'bro my prof opened his social media on accident and he\'s following several vtubers wtf',
  'resisting the urge to yell OBJECTION in my law class',
  'I will only accept data centers if they give us AI girlfriends.',
  'If the prof doesn\'t curve, I might have some trouble. But would I lose? Nah, I\'d win.',
  'the venus statue tiddy situation is crazy',
  'Lowrise 3 sunday dinner better make me grow 3 inches taller considering the waitlist is longer than the goddamn housing queue',
  'the freights reading nook curtains are NOT soundproof!! we ALL HEAR YOU',
  'Concordia et prosperitas motherfuckers!!',
  'nothing beats the adrenaline of the reserve bank line at 8:55 when class is at 9',
  'don\'t give up, bio skeleton!',
  'you need more than touching grass. try some touching ass',
  'lowrise 5 elevator is broken again. 6th floor. im dying',
  'WHO microwaved fish in the lowrise 3 kitchen',
  'The thought that you will soon be done with the reading fills you with determination.',
  'Get busy studying, or get busy failing.',
  'one world one love but the battle goes on shadows of mass, destruction',
  'with no power comes no responsibility',
  'my xp bar is low',
  'BITCH IM BACK OUT MY COMA',
  'been meaning to text back for 9 days. at this point its awkward',
  'reading day and the whole quad is at selkie. wheres your motivation!?',
  'no one TA should have all that power',
  'CAN WE GET MUCH HIGHER?? (so high)',
  'i never thought i could get tired of an eternal spring but here we are welcome to veridan',
  'Petition for the Loop to stop at the Stalestein after 2am',
  'so your telling me thorne can book any celebrity on earth for the auditorium and he books a guy who plays the spoons',
  'hnnnnnnnnnnnnnnn let\'s larp',
  'selkie sand comes in on a BARGE. im not at the beach this is a bathtub!',
  'campus at 2am is a different game entirely',
  'someone put a hat on the traffic cone outside thorne. best thing on campus',
  'curve THIS motherfucker',
  'fought a guy for the last chair in the library. we\'re friends now',
  'been humming a song for 3 days and cant remember what it is. its ruining my life',
  'Mr.Thorne is helping me find my homework.',
  'I LEARNED TO COOK SOMETHING! lowrise 4 has now eaten it eleven times',
  'hour 30 of being awake and everything is funny',
  'What the hell is wrong with "HORNY"? If all you guys are not "HORNY", the human race will perish, LOL',
  'With this breakup, the thread of prophecy is severed. Restore a saved game to restore the weave of fate, or persist in the doomed world I have created?',
  'Out, out, brief candle! A freshman is but a walking shadow, a poor player that struts and frets his hour upon the podium and is heard no more...',
  'with this treasure i summon... eight-spice eastern buffet general tsos chicken',
  'da da da it is good day to not be dead'
]

/** Faces the campus posts under — an emoji stands in for a photo. */
export const FEED_EMOJI: readonly string[] = [
  '🐧',
  '🍜',
  '🌵',
  '🦉',
  '🫖',
  '🛼',
  '🌗',
  '🧃',
  '🐌',
  '🎧',
  '🪴',
  '🧊',
  '🦆',
  '📎',
  '🍄',
  '🧦',
  '🪐',
  '🐙',
  '🥐',
  '🕯️',
  '🦖',
  '🧶',
  '🌪️',
  '🍋',
  '🎷',
  '🐈',
  '🪁',
  '🥁',
  '🌊',
  '🍥'
]
